apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ead-ca201
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kajaldevopsengineer/backend-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "mongodb+srv://ead2024:ead2024.@ead-2023-24.lpclwdo.mongodb.net/?retryWrites=true&w=majority"
            - name: DATABASE_NAME
              value: "ead_ca2"
            - name: DATABASE_COLLECTION
              value: "ead_2024"
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"