apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ead-ca201
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: acreaadca2012104262113.azurecr.io/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22137