name: Monitoring Setup

on:
  workflow_dispatch:

jobs:
  monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Prometheus & Grafana
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          kubectl create namespace monitoring || true
          helm install monitoring prometheus-community/kube-prometheus-stack -n monitoring